@extends('fontend.main')

@section('main_container')
<div class="header_center">
    <h3 style="text-align: center;">Terms And Conditions</h3>
    <hr>
    <h3>Shipping Policy and Information</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui esse eveniet repellendus cum explicabo quia corrupti optio et ducimus in ab velit ad doloribus beatae totam, id vitae? Autem repudiandae maiores beatae ipsum sunt laborum iusto aut recusandae in voluptatibus nisi a cumque ducimus dolores accusamus exercitationem rem quam sint libero, laboriosam asperiores fuga tempora reiciendis? Delectus repellat quidem ab tenetur autem quibusdam repudiandae aspernatur consequuntur nulla dolor reiciendis assumenda officiis magni dolore eos atque quia ipsum quam, commodi porro dolorem placeat excepturi ex non. Nihil quas perferendis sequi incidunt enim illum, assumenda, officiis aut veniam dignissimos earum rerum suscipit.</p>
    <h3>Shipping Restriction</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui esse eveniet repellendus cum explicabo quia corrupti optio et ducimus in ab velit ad doloribus beatae totam, id vitae? Autem repudiandae maiores beatae ipsum sunt laborum iusto aut recusandae in voluptatibus nisi a cumque ducimus dolores accusamus exercitationem rem quam sint libero, laboriosam asperiores fuga tempora reiciendis? Delectus repellat quidem ab tenetur autem quibusdam repudiandae aspernatur consequuntur nulla dolor reiciendis assumenda officiis magni dolore eos atque quia ipsum quam, commodi porro dolorem placeat excepturi ex non. Nihil quas perferendis sequi incidunt enim illum, assumenda, officiis aut veniam dignissimos earum rerum suscipit.</p>
    <h3>Important Information</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui esse eveniet repellendus cum explicabo quia corrupti optio et ducimus in ab velit ad doloribus beatae totam, id vitae? Autem repudiandae maiores beatae ipsum sunt laborum iusto aut recusandae in voluptatibus nisi a cumque ducimus dolores accusamus exercitationem rem quam sint libero, laboriosam asperiores fuga tempora reiciendis? Delectus repellat quidem ab tenetur autem quibusdam repudiandae aspernatur consequuntur nulla dolor reiciendis assumenda officiis magni dolore eos atque quia ipsum quam, commodi porro dolorem placeat excepturi ex non. Nihil quas perferendis sequi incidunt enim illum, assumenda, officiis aut veniam dignissimos earum rerum suscipit.</p>
    <h3>When do we Deliver</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui esse eveniet repellendus cum explicabo quia corrupti optio et ducimus in ab velit ad doloribus beatae totam, id vitae? Autem repudiandae maiores beatae ipsum sunt laborum iusto aut recusandae in voluptatibus nisi a cumque ducimus dolores accusamus exercitationem rem quam sint libero, laboriosam asperiores fuga tempora reiciendis? Delectus repellat quidem ab tenetur autem quibusdam repudiandae aspernatur consequuntur nulla dolor reiciendis assumenda officiis magni dolore eos atque quia ipsum quam, commodi porro dolorem placeat excepturi ex non. Nihil quas perferendis sequi incidunt enim illum, assumenda, officiis aut veniam dignissimos earum rerum suscipit.</p>
    <h3>Shipping in India</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui esse eveniet repellendus cum explicabo quia corrupti optio et ducimus in ab velit ad doloribus beatae totam, id vitae? Autem repudiandae maiores beatae ipsum sunt laborum iusto aut recusandae in voluptatibus nisi a cumque ducimus dolores accusamus exercitationem rem quam sint libero, laboriosam asperiores fuga tempora reiciendis? Delectus repellat quidem ab tenetur autem quibusdam repudiandae aspernatur consequuntur nulla dolor reiciendis assumenda officiis magni dolore eos atque quia ipsum quam, commodi porro dolorem placeat excepturi ex non. Nihil quas perferendis sequi incidunt enim illum, assumenda, officiis aut veniam dignissimos earum rerum suscipit.</p>
    <h3>International Shipping</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui esse eveniet repellendus cum explicabo quia corrupti optio et ducimus in ab velit ad doloribus beatae totam, id vitae? Autem repudiandae maiores beatae ipsum sunt laborum iusto aut recusandae in voluptatibus nisi a cumque ducimus dolores accusamus exercitationem rem quam sint libero, laboriosam asperiores fuga tempora reiciendis? Delectus repellat quidem ab tenetur autem quibusdam repudiandae aspernatur consequuntur nulla dolor reiciendis assumenda officiis magni dolore eos atque quia ipsum quam, commodi porro dolorem placeat excepturi ex non. Nihil quas perferendis sequi incidunt enim illum, assumenda, officiis aut veniam dignissimos earum rerum suscipit.</p>

</div>
@endsection